/**
 * Created by Administrator on 2016/12/23 0023.
 */

//菜单栏切换
export const CHANGE_MENU_TAB= 'CHANGE_MENU_TAB';  
export const CHANGE_SUB_NAV = 'CHANGE_SUB_NAV';

//发送请求
export const BEGIN_FETCH = 'BEGIN_FETCH';
export const FALL_FETCH = 'FALL_FETCH';


//公共部分：
export const SHOW_SUCCESS = 'SHOW_SUCCESS';     //tips提示
export const SHOW_ERROR = 'SHOW_ERROR';     //tips提示
export const SHOW_DIALOG = 'SHOW_DIALOG';    //DIALOG 提示
export const SHOW_TOAST_LOADING = 'SHOW_TOAST_LOADING';    // Toast 提示（正在发表评论、发表评论成功）
export const SHOW_TOAST_SUCCESS = 'SHOW_TOAST_SUCCESS';    // Toast 提示（正在发表评论、发表评论成功）
export const SHOW_FULL_POPUP = 'SHOW_FULL_POPUP';  //显示满屏幕的 popup
export const SHOW_PAY_POPUP = 'SHOW_PAY_POPUP';     //付款提示
export const GET_CIPHERTEXT_SUCCESS = 'GET_CIPHERTEXT_SUCCESS';     //支付
export const CHANGE_SWIPE_INDEX = 'CHANGE_SWIPE_INDEX';   //滚动分页
export const GET_RECOMMENDED_LIST_SUCCESS = 'GET_RECOMMENDED_LIST_SUCCESS';  //推荐列表获取成功


//登录 注册
export const CHANGE_TAP = 'CHANGE_TAP';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_IMG_UPLOAD = 'SUCCESS_IMG_UPLOAD';
export const COUNT_DOWN = 'COUNT_DOWN';
export const SET_INTERESTING_LIST = 'SET_INTERESTING_LIST';
// export const GET_PHONE = 'GET_PHONE';
// export const GET_PASSWORD = 'GET_PASSWORD';


//首页
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_ICBC_BTN_SUCCESS = 'GET_ICBC_BTN_SUCCESS';
export const GET_HOME_CONTENTLIST_SUCCESS = 'GET_HOME_CONTENTLIST_SUCCESS';



//评论
export const BEGIN_GET_COMMENT = 'BEGIN_GET_COMMENT';
export const DONE_GET_COMMENT = 'DONE_GET_COMMENT';
export const FAIL_GET_COMMENT = 'FAIL_GET_COMMENT';
export const CHANGE_HEADERSTR = 'CHANGE_HEADERSTR';
export const CHANGE_COMMENT_VALUE = 'CHANGE_COMMENT_VALUE';
export const CHAGNE_PUBLISH_IMGLIST = 'CHAGNE_PUBLISH_IMGLIST';



//活动 列表
export const DONE_GET_ActList = 'DONE_GET_ActList';
export const POPUP = 'POPUP';
export const SUBMIT_ACTINFO_SUCCESS = 'SUBMIT_ACTINFO_SUCCESS';
//活动详情
export const DONE_GET_DETAIL = 'DONE_GET_DETAIL';
export const DONE_GET_ACTSTATU = 'DONE_GET_ACTSTATU';
export const DONE_GET_ACTCOMMENT = 'DONE_GET_ACTCOMMENT';
export const ACT_SHOW_MORE = 'ACT_SHOW_MORE';
export const ACT_SHOW_BACK_TOP = 'ACT_SHOW_BACK_TOP';
export const GET_USER_JOINACT_STATUS = 'GET_USER_JOINACT_STATUS';


//课程 列表
export const DONE_GET_COURSELIST = 'DONE_GET_COURSELIST';
    /*课程详情*/
export const DONE_GET_COURSEDETAIL = 'DONE_GET_COURSEDETAIL';
export const SHOW_MORE_COURSEDETAIL = 'SHOW_MORE_COURSEDETAIL';
export const SHOW_BACK_TOP = 'SHOW_BACK_TOP';
export const POP_LEFT_BUYBAR = 'POP_LEFT_BUYBAR';
export const CHOOSE_ITEM = 'CHOOSE_ITEM';
export const INIT_CHOOSEDATA = 'INIT_CHOOSEDATA';
    //获取 视频真的 URL
export const GET_REAL_VEDIOURL = 'GET_REAL_VEDIOURL';
    

// 臻品详情
export const GET_GOODDETAIL_SUCCESS = 'GET_GOODDETAIL_SUCCESS';
export const GET_SKULIST_SUCCESS = 'GET_SKULIST_SUCCESS';
export const CHANGE_CHOOSE_SKU = 'CHANGE_CHOOSE_SKU';


//个人信息
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';
export const GET_BANKLIST_SUCCESS = 'GET_BANKLIST_SUCCESS';
export const SET_USERINFO_SUCCESS = 'SET_USERINFO_SUCCESS';
export const SET_HEADPIC_SUCCESS = 'SET_HEADPIC_SUCCESS';
    // 上传反馈图片
export const SET_FEEDBACK_SHOW = 'SET_FEEDBACK_SHOW';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const CAHNGE_POST_IMGLIST = 'CAHNGE_POST_IMGLIST';
    //我的课程
export const GET_MYCOURSELIST_SUCCESS = 'GET_MYCOURSELIST_SUCCESS';
    //我的礼包
export const GET_MYGIFTSLIST_SUCCESS = 'GET_MYGIFTSLIST_SUCCESS';
export const GET_GIFTDETAIL_SUCCESS = 'GET_GIFTDETAIL_SUCCESS';
    //地址
export const GET_ADDRESSLIST_SUCCESS = 'GET_ADDRESSLIST_SUCCESS';
export const SET_DEFAULTADDRESS_SUCCESS = 'SET_DEFAULTADDRESS_SUCCESS';
    //我的订单
export const ORDER_LOADING = 'ORDER_LOADING';
export const GET_ORDERLIST_SUCCESS = 'GET_ORDERLIST_SUCCESS';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const GET_ORDER_ADDRESS = 'GET_ORDER_ADDRESS';
   




